### ISSUE TITLE
Linux/cross-platform support

### ISSUE THREAD

**Issue by radgeRayden** [jbikker/WrldTmpl8#1]
I wanted very badly to try this, but it seems tied to windows and to some extent visual studio (which I can't justify installing, unfortunately). I tried to hack at it myself (and submit a PR) but noticed it is not just a matter of modifying some ifdefs, as some windows API code is used.
The easy parts:
- adding ifdefs around use of windows.h.
- windows is case insensitive when looking for files, but it isn't the case on Unix based systems. `#include <cl/cl.h>` should be `#include <CL/cl.h>`.
- would be nice to have a makefile, but the project is simple enough.
- defining correct macros for glfw native, like `GLFW_EXPOSE_NATIVE_X11`, and using the appropriate context functions to pass ogl context to opencl.
- This may be ignorance on my part, but I got a lot of errors about `<cstring>` functions being used without being defined. An include may be missing or I made a mistake when trying to build.

There are some parts that would require actual work. The first I noticed is that windows API synchronization functions are used for jobs. An alternative would have to be provided if you intend to support other OSs.

Either way, thanks for sharing, it is valuable for study even if I can't see it in action right away.

**Comment by jbikker** [comment]
Hi,
I am not a Linux person myself, but students did already make the original 'Templ8' cross-platform:
https://github.com/jbikker/tmpl8
This template shows a lot of overlap with the voxel world template, so it may be possible to simply merge them.
The only exception is the job system. In the voxel world template this is used to speed up the streaming memcpy. Luckily, the impact of this optimization is small; you can simply do the memcpy in a single thread to bypass the job code.
By the way, I intend to use the voxel template for an updated C/C++ course based on these materials:
https://www.3dgep.com/cpp-fast-track-1-getting-started/
This will assume Windows as a platform for beginning developers.
- Jacco.
