### ISSUE TITLE
incorrect commitSize ?

### ISSUE THREAD

**Issue by debaetsd** [jbikker/WrldTmpl8#2]
World.cpp is defining `static const uint commitSize = BRICKCOMMITSIZE / 4 + gridSize;`
Why the div by 4 ? I think this makes the commit buffer to small ? (commit buffer is `commit` in code, not `commitBuffer` (not used anymore?))

I added some quick&dirty frame-sliced commits (only upload MAXCOMMITS each frame, remaining are done next frames) so I don't have to bump the MAXCOMMITS exponential. 

This however leads to a crash during StreamCopy (during World::Commit, dst pointer is not writable) and I believe this is due the buffer not allocated big enough to actually hold MAXCOMMITS bricks+Indices?

Quickly inspecting it I wonder why this div by 4 is done.
Not doing that div works but it could be just masking the symptoms ?

**Comment by jbikker** [comment]
The commitSize is in 32-bit values, not bytes. This is a leftover from the Buffer class, which always assumes 32-bit elements. It's not pretty, so perhaps it's better to convert this to bytes everywhere.
I removed the unused commitBuffer. This triggered a bug, where OpenCL is not initialized before the API is used. This is now fixed.
Regarding the MAXCOMMITS: each brick is 512 bytes, so 8192 bricks as a maximum is 4MB of data. You would be safe with at least twice that (top-level is also 8MB, budget per second is at least 10GB these days). But, maybe you should consider why you have too many commits: After executing Game::Init, the template copies all bricks to VRAM unconditionally. You should do scene setup here, and then have smaller changes in Game::Tick.
I do believe the commit system should pickup an overflow, and trigger a full copy in that case, with a warning.

**Comment by jbikker** [comment]
The sizes are now all converted to bytes: commitSize, gridSize, but also the arguments of the streaming copy functions. I think this is a lot clearer.

**Comment by debaetsd** [comment]
> maybe you should consider why you have too many commits

I'm injecting close to 2million voxels during init 👿 

With the latest changes (conversion to bytes), it works fine (with my temporal uploaded hacks) so maybe some bug was lingering in there that got fixed now ? Definably  a lot cleaner

anyway, it works now :)
For what it is worth, these are my changes:
```
--- a/template/world.cpp
+++ b/template/world.cpp
@@ -479,7 +479,10 @@ void World::Commit()
                *idx++ = (uint)i; // store index of modified brick at start of commit buffer
                StreamCopy( (__m256i*)dst, (__m256i*)(brick + i * BRICKSIZE), BRICKSIZE );
                dst += BRICKSIZE, tasks++;
+               ResetDirty(i);
+               if (tasks >= MAXCOMMITS - 1) goto stopit;
        }
+       stopit:
        // asynchroneously copy the CPU data to the GPU via the commit buffer
        if (tasks > 0 || firstFrame)
        {
@@ -502,7 +505,7 @@ void World::Commit()
                firstFrame = false;
        }
        // reset the bitfield for the next frame
-       ClearMarks();
+       //ClearMarks();
 }
```
not the most efficient but works for me

**Comment by jbikker** [comment]
I implemented something along those lines. Good solution for now.
