### ISSUE TITLE
Two fatal errors at launch

### ISSUE THREAD

**Issue by BenjaminGu** [jbikker/WrldTmpl8#8]
![image](https://user-images.githubusercontent.com/16999381/143219587-7db51d71-53d1-41f6-a841-6df9ba769443.png)

![image](https://user-images.githubusercontent.com/16999381/143219398-f6cf24b2-bce8-464f-b823-7d5a6585f863.png)

**Comment by jbikker** [comment]
Thanks for reporting this. These have now been resolved, but I am surprised that you encountered the first one: 'r' should be a valid alias for 'x' in OpenCL. Nevertheless, the issue has been resolved. Let me know if you find anything else.
